### ISSUE TITLE
Change Password feature not working

### ISSUE THREAD

**Issue by hungtrquoc** [shopizer-ecommerce/shopizer#325]
change password feature not working with generic theme.

**Comment by shopizer-ecommerce** [comment]
Change password not working for customer ?

**Comment by hungtrquoc** [comment]
yup. for customer. And forget password for admin not working too.

**Comment by shopizer-ecommerce** [comment]
Ok thanks will check Customer

For Admin, new version will be released within 1 week. I will update this ticket

**Comment by shopizer-ecommerce** [comment]
Fixed change password in master, will be available in 2.5.0 (2 weeks), in the meantime 
     CustomerAccoutController must have those changes


    	String currentPassword = password.getCurrentPassword();

    	BCryptPasswordEncoder encoder = (BCryptPasswordEncoder)passwordEncoder;
    	if(!encoder.matches(currentPassword, customer.getPassword())) {
          FieldError error = new FieldError("password","password",messages.getMessage("message.invalidpassword", locale));
          bindingResult.addError(error);
    	}

**Comment by hungtrquoc** [comment]
this function is still not working, pls help to check and reopen this issue. thanks

**Comment by serdarekcx** [comment]
what a product is this common features is not working ?


Trần Quốc Hùng <notifications@github.com>, 7 Nis 2019 Paz, 09:03 tarihinde
şunu yazdı:

**Comment by shopizer-ecommerce** [comment]
It was fixed and tested in generic theme

Have you tried version 2.5.0 ?

**Comment by hungtrquoc** [comment]
![image](https://user-images.githubusercontent.com/4296584/57564460-2ad04a80-73d6-11e9-874d-a9a004a1bc31.png)

**Comment by hungtrquoc** [comment]
i have updated to 2.5.0

**Comment by bevrard** [comment]
The issue comes from logon.jsp:
```
function getUserInformation() {
					 // get the form values 
					$('#securityQtn1Select').empty();
					$('#securityQtn2Select').empty();
					$('#securityQtn3Select').empty();
					$('#answer1').val('');
					$('#answer2').val('');
					$('#answer3').val('');
					var userName = $('#username').val();
```
$('#username').val(); is a reference to the form to loginForm.  So the value is always empty.
The line should target the resetPasswordForm:
```
$('#resetPasswordForm #username').val()
```
