### ISSUE TITLE
Not able to run clean install. Version 2.0.2

### ISSUE THREAD

**Issue by mohankv** [shopizer-ecommerce/shopizer#36]
$ mvn clean install
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] 'dependencies.dependency.version' for com.shopizer:sm-core-model:jar must be a valid version but is '${sm-core-model.version}'. @ com.shopizer:sm-core:[unknown-version], /Volumes/A/myProjects/shopizer/shopizer/sm-core/pom.xml, line 58, column 13
[ERROR] 'dependencies.dependency.version' for com.shopizer:sm-core-modules:jar must be a valid version but is '${sm-core-modules.version}'. @ com.shopizer:sm-core:[unknown-version], /Volumes/A/myProjects/shopizer/shopizer/sm-core/pom.xml, line 65, column 13
[ERROR] 'dependencies.dependency.version' for com.shopizer:sm-search:jar must be a valid version but is '${sm-search.version}'. @ com.shopizer:sm-core:[unknown-version], /Volumes/A/myProjects/shopizer/shopizer/sm-core/pom.xml, line 72, column 13
[WARNING] 'build.pluginManagement.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.bsc.maven:maven-processor-plugin @ com.shopizer:sm-core-model:[unknown-version], /Volumes/A/myProjects/shopizer/shopizer/sm-core-model/pom.xml, line 426, column 13
[ERROR] 'dependencies.dependency.version' for com.shopizer:sm-core-model:jar must be a valid version but is '${sm-core-model.version}'. @ com.shopizer:sm-core-modules:[unknown-version], /Volumes/A/myProjects/shopizer/shopizer/sm-core-modules/pom.xml, line 30, column 13
[ERROR] 'dependencies.dependency.version' for com.shopizer:sm-core:jar must be a valid version but is '${sm-core.version}'. @ com.salesmanager:sm-shop:[unknown-version], /Volumes/A/myProjects/shopizer/shopizer/sm-shop/pom.xml, line 42, column 13
[ERROR] 'dependencies.dependency.version' for com.shopizer:sm-core-model:jar must be a valid version but is '${sm-core-model.version}'. @ com.salesmanager:sm-shop:[unknown-version], /Volumes/A/myProjects/shopizer/shopizer/sm-shop/pom.xml, line 49, column 13
[ERROR] 'dependencies.dependency.version' for com.shopizer:sm-core-modules:jar must be a valid version but is '${sm-core-modules.version}'. @ com.salesmanager:sm-shop:[unknown-version], /Volumes/A/myProjects/shopizer/shopizer/sm-shop/pom.xml, line 56, column 13
[ERROR] 'dependencies.dependency.version' for com.shopizer:sm-search:jar must be a valid version but is '${sm-search.version}'. @ com.salesmanager:sm-shop:[unknown-version], /Volumes/A/myProjects/shopizer/shopizer/sm-shop/pom.xml, line 64, column 13
[ERROR] 'dependencies.dependency.version' for com.shopizer:shopizer-shipping-canadapost-module:jar must be a valid version but is '${shopizer-canadapost.version}'. @ com.salesmanager:sm-shop:[unknown-version], /Volumes/A/myProjects/shopizer/shopizer/sm-shop/pom.xml, line 71, column 13
 @ 
[ERROR] The build could not read 3 projects -> [Help 1]
[ERROR]   
[ERROR]   The project com.shopizer:sm-core:0.0.1-SNAPSHOT (/Volumes/A/myProjects/shopizer/shopizer/sm-core/pom.xml) has 3 errors
[ERROR]     'dependencies.dependency.version' for com.shopizer:sm-core-model:jar must be a valid version but is '${sm-core-model.version}'. @ com.shopizer:sm-core:[unknown-version], /Volumes/A/myProjects/shopizer/shopizer/sm-core/pom.xml, line 58, column 13
[ERROR]     'dependencies.dependency.version' for com.shopizer:sm-core-modules:jar must be a valid version but is '${sm-core-modules.version}'. @ com.shopizer:sm-core:[unknown-version], /Volumes/A/myProjects/shopizer/shopizer/sm-core/pom.xml, line 65, column 13
[ERROR]     'dependencies.dependency.version' for com.shopizer:sm-search:jar must be a valid version but is '${sm-search.version}'. @ com.shopizer:sm-core:[unknown-version], /Volumes/A/myProjects/shopizer/shopizer/sm-core/pom.xml, line 72, column 13
[ERROR]   
[ERROR]   The project com.shopizer:sm-core-modules:0.0.1-SNAPSHOT (/Volumes/A/myProjects/shopizer/shopizer/sm-core-modules/pom.xml) has 1 error
[ERROR]     'dependencies.dependency.version' for com.shopizer:sm-core-model:jar must be a valid version but is '${sm-core-model.version}'. @ com.shopizer:sm-core-modules:[unknown-version], /Volumes/A/myProjects/shopizer/shopizer/sm-core-modules/pom.xml, line 30, column 13
[ERROR]   
[ERROR]   The project com.salesmanager:sm-shop:0.0.1-SNAPSHOT (/Volumes/A/myProjects/shopizer/shopizer/sm-shop/pom.xml) has 5 errors
[ERROR]     'dependencies.dependency.version' for com.shopizer:sm-core:jar must be a valid version but is '${sm-core.version}'. @ com.salesmanager:sm-shop:[unknown-version], /Volumes/A/myProjects/shopizer/shopizer/sm-shop/pom.xml, line 42, column 13
[ERROR]     'dependencies.dependency.version' for com.shopizer:sm-core-model:jar must be a valid version but is '${sm-core-model.version}'. @ com.salesmanager:sm-shop:[unknown-version], /Volumes/A/myProjects/shopizer/shopizer/sm-shop/pom.xml, line 49, column 13
[ERROR]     'dependencies.dependency.version' for com.shopizer:sm-core-modules:jar must be a valid version but is '${sm-core-modules.version}'. @ com.salesmanager:sm-shop:[unknown-version], /Volumes/A/myProjects/shopizer/shopizer/sm-shop/pom.xml, line 56, column 13
[ERROR]     'dependencies.dependency.version' for com.shopizer:sm-search:jar must be a valid version but is '${sm-search.version}'. @ com.salesmanager:sm-shop:[unknown-version], /Volumes/A/myProjects/shopizer/shopizer/sm-shop/pom.xml, line 64, column 13
[ERROR]     'dependencies.dependency.version' for com.shopizer:shopizer-shipping-canadapost-module:jar must be a valid version but is '${shopizer-canadapost.version}'. @ com.salesmanager:sm-shop:[unknown-version], /Volumes/A/myProjects/shopizer/shopizer/sm-shop/pom.xml, line 71, column 13
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException

**Comment by shopizer-ecommerce** [comment]
are you doing

cd shopizer

mvn clean install

**Comment by mohankv** [comment]
correct. 

MBP:shopizer mk$ pwd
/Volumes/A/myProjects/shopizer/shopizer
MBP:shopizer mk$ ls
bin             sm-core         sm-core-modules
pom.xml         sm-core-model   sm-shop
MBP:shopizer mk$ mvn clean install
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] 'dependencies.dependency.version' for com.shopizer:sm-core-model:jar must be a valid version but is '${sm-core-model.version}'. @ com.shopizer:sm-core:[unknown-version], /Volumes/A/myProjects/shopizer/shopizer/sm-core/pom.xml, line 58, column 13
[ERROR] 'dependencies.dependency.version' for com.shopizer:sm-core-modules:jar must be a valid version but is '${sm-core-modules.version}'. @ com.shopizer:sm-core:[unknown-version], /Volumes/A/myProjects/shopizer/shopizer/sm-core/pom.xml, line 65, column 13
[ERROR] 'dependencies.dependency.version' for com.shopizer:sm-search:jar must be a valid version but is '${sm-search.version}'. @ com.shopizer:sm-core:[unknown-version], /Volumes/A/myProjects/shopizer/shopizer/sm-core/pom.xml, line 72, column 13
[WARNING] 'build.pluginManagement.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.bsc.maven:maven-processor-plugin @ com.shopizer:sm-core-model:[unknown-version], /Volumes/A/myProjects/shopizer/shopizer/sm-core-model/pom.xml, line 426, column 13
[ERROR] 'dependencies.dependency.version' for com.shopizer:sm-core-model:jar must be a valid version but is '${sm-core-model.version}'. @ com.shopizer:sm-core-modules:[unknown-version], /Volumes/A/myProjects/shopizer/shopizer/sm-core-modules/pom.xml, line 30, column 13
[ERROR] 'dependencies.dependency.version' for com.shopizer:sm-core:jar must be a valid version but is '${sm-core.version}'. @ com.salesmanager:sm-shop:[unknown-version], /Volumes/A/myProjects/shopizer/shopizer/sm-shop/pom.xml, line 42, column 13
[ERROR] 'dependencies.dependency.version' for com.shopizer:sm-core-model:jar must be a valid version but is '${sm-core-model.version}'. @ com.salesmanager:sm-shop:[unknown-version], /Volumes/A/myProjects/shopizer/shopizer/sm-shop/pom.xml, line 49, column 13
[ERROR] 'dependencies.dependency.version' for com.shopizer:sm-core-modules:jar must be a valid version but is '${sm-core-modules.version}'. @ com.salesmanager:sm-shop:[unknown-version], /Volumes/A/myProjects/shopizer/shopizer/sm-shop/pom.xml, line 56, column 13
[ERROR] 'dependencies.dependency.version' for com.shopizer:sm-search:jar must be a valid version but is '${sm-search.version}'. @ com.salesmanager:sm-shop:[unknown-version], /Volumes/A/myProjects/shopizer/shopizer/sm-shop/pom.xml, line 64, column 13
[ERROR] 'dependencies.dependency.version' for com.shopizer:shopizer-shipping-canadapost-module:jar must be a valid version but is '${shopizer-canadapost.version}'. @ com.salesmanager:sm-shop:[unknown-version], /Volumes/A/myProjects/shopizer/shopizer/sm-shop/pom.xml, line 71, column 13
 @ 
[ERROR] The build could not read 3 projects -> [Help 1]
[ERROR]   
[ERROR]   The project com.shopizer:sm-core:0.0.1-SNAPSHOT (/Volumes/A/myProjects/shopizer/shopizer/sm-core/pom.xml) has 3 errors
[ERROR]     'dependencies.dependency.version' for com.shopizer:sm-core-model:jar must be a valid version but is '${sm-core-model.version}'. @ com.shopizer:sm-core:[unknown-version], /Volumes/A/myProjects/shopizer/shopizer/sm-core/pom.xml, line 58, column 13
[ERROR]     'dependencies.dependency.version' for com.shopizer:sm-core-modules:jar must be a valid version but is '${sm-core-modules.version}'. @ com.shopizer:sm-core:[unknown-version], /Volumes/A/myProjects/shopizer/shopizer/sm-core/pom.xml, line 65, column 13
[ERROR]     'dependencies.dependency.version' for com.shopizer:sm-search:jar must be a valid version but is '${sm-search.version}'. @ com.shopizer:sm-core:[unknown-version], /Volumes/A/myProjects/shopizer/shopizer/sm-core/pom.xml, line 72, column 13
[ERROR]   
[ERROR]   The project com.shopizer:sm-core-modules:0.0.1-SNAPSHOT (/Volumes/A/myProjects/shopizer/shopizer/sm-core-modules/pom.xml) has 1 error
[ERROR]     'dependencies.dependency.version' for com.shopizer:sm-core-model:jar must be a valid version but is '${sm-core-model.version}'. @ com.shopizer:sm-core-modules:[unknown-version], /Volumes/A/myProjects/shopizer/shopizer/sm-core-modules/pom.xml, line 30, column 13
[ERROR]   
[ERROR]   The project com.salesmanager:sm-shop:0.0.1-SNAPSHOT (/Volumes/A/myProjects/shopizer/shopizer/sm-shop/pom.xml) has 5 errors
[ERROR]     'dependencies.dependency.version' for com.shopizer:sm-core:jar must be a valid version but is '${sm-core.version}'. @ com.salesmanager:sm-shop:[unknown-version], /Volumes/A/myProjects/shopizer/shopizer/sm-shop/pom.xml, line 42, column 13
[ERROR]     'dependencies.dependency.version' for com.shopizer:sm-core-model:jar must be a valid version but is '${sm-core-model.version}'. @ com.salesmanager:sm-shop:[unknown-version], /Volumes/A/myProjects/shopizer/shopizer/sm-shop/pom.xml, line 49, column 13
[ERROR]     'dependencies.dependency.version' for com.shopizer:sm-core-modules:jar must be a valid version but is '${sm-core-modules.version}'. @ com.salesmanager:sm-shop:[unknown-version], /Volumes/A/myProjects/shopizer/shopizer/sm-shop/pom.xml, line 56, column 13
[ERROR]     'dependencies.dependency.version' for com.shopizer:sm-search:jar must be a valid version but is '${sm-search.version}'. @ com.salesmanager:sm-shop:[unknown-version], /Volumes/A/myProjects/shopizer/shopizer/sm-shop/pom.xml, line 64, column 13
[ERROR]     'dependencies.dependency.version' for com.shopizer:shopizer-shipping-canadapost-module:jar must be a valid version but is '${shopizer-canadapost.version}'. @ com.salesmanager:sm-shop:[unknown-version], /Volumes/A/myProjects/shopizer/shopizer/sm-shop/pom.xml, line 71, column 13
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException

**Comment by poornacv** [comment]
Yes, even i have faced many issue but finally fixed all of them. 

I have added these properties in required pom.xml for respective modules and also replaced <java.version> tag in sm-shop/pom.xml to <jdk.version>

**Comment by shopizer-ecommerce** [comment]
Thanks, we unfortunately missed the parent POM, all versions are fixed now

**Comment by mohankv** [comment]
Thanks for fixing these. I still see some errors.

MBP:shopizer mk$ ls
LICENSE.md       README.md        RELEASE-NOTES.md shopizer
MBP:shopizer mk$ cd shopizer/
MBP:shopizer mk$ ls
pom.xml         sm-core-model   sm-shop
sm-core         sm-core-modules
MBP:shopizer mk$ mvn clean install
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.shopizer:sm-core-model:jar:0.0.1-SNAPSHOT
[WARNING] 'build.pluginManagement.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.bsc.maven:maven-processor-plugin @ com.shopizer:sm-core-model:[unknown-version], /Volumes/A/myProjects/shopizer/shopizer/sm-core-model/pom.xml, line 426, column 13
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] sm-core
[INFO] sm-core-model
[INFO] sm-core-modules
[INFO] sm-shop
[INFO] shopizer
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building sm-core 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.shopizer:sm-core-model:jar:2.0.2-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for com.shopizer:sm-core-modules:jar:2.0.2-SNAPSHOT is missing, no dependency information available
[WARNING] The artifact aspectj:aspectjrt:jar:1.5.4 has been relocated to org.aspectj:aspectjrt:jar:1.5.4
[WARNING] The artifact aspectj:aspectjweaver:jar:1.5.4 has been relocated to org.aspectj:aspectjweaver:jar:1.5.4
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] sm-core ............................................ FAILURE [  0.928 s]
[INFO] sm-core-model ...................................... SKIPPED
[INFO] sm-core-modules .................................... SKIPPED
[INFO] sm-shop ............................................ SKIPPED
[INFO] shopizer ........................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.072 s
[INFO] Finished at: 2015-07-31T10:11:30-05:00
[INFO] Final Memory: 11M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project sm-core: Could not resolve dependencies for project com.shopizer:sm-core:jar:0.0.1-SNAPSHOT: The following artifacts could not be resolved: com.shopizer:sm-core-model:jar:2.0.2-SNAPSHOT, com.shopizer:sm-core-modules:jar:2.0.2-SNAPSHOT: Failure to find com.shopizer:sm-core-model:jar:2.0.2-SNAPSHOT in http://maven.springframework.org/snapshot was cached in the local repository, resolution will not be reattempted until the update interval of org.springframework.maven.snapshot has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by punj** [comment]
hi! mohankv,

Same problem here. Got any solution?

Thanks in advance!

**Comment by poojawarudkar** [comment]
Seeing the same issue - not able to compile sm-shop. 

[ERROR] Failed to execute goal on project sm-shop: Could not resolve dependencies for project com.salesmanager:sm-shop:war:0.0.1-SNAPSHOT: Could not find artifact com.shopizer:sm-core:jar:0.0.2-SNAPSHOT in org.springframework.maven.snapshot (http://maven.springframework.org/snapshot) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by umeshawasthi** [comment]
Can you share complete log ??? and how you are running the build?

On Mon, Aug 17, 2015 at 9:22 AM, poojawarudkar <notifications@github.com>
wrote:

> Seeing the same issue - not able to compile sm-shop.
>
> [ERROR] Failed to execute goal on project sm-shop: Could not resolve
> dependencies for project com.salesmanager:sm-shop:war:0.0.1-SNAPSHOT: Could
> not find artifact com.shopizer:sm-core:jar:0.0.2-SNAPSHOT in
> org.springframework.maven.snapshot (
> http://maven.springframework.org/snapshot) -> [Help 1]
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with the
> -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions,
> please read the following articles:
> [ERROR] [Help 1]
> http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shopizer-ecommerce/shopizer/issues/36#issuecomment-131878636>
> .
>



-- 
With Regards
Umesh Awasthi
http://www.travellingrants.com/

**Comment by poojawarudkar** [comment]
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.shopizer:sm-core-model:war:0.0.1-SNAPSHOT
[WARNING] 'build.pluginManagement.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.bsc.maven:maven-processor-plugin @ com.shopizer:sm-core-model:[unknown-version], /Users/poojawarudkar/shopizer-2.0.2/shopizer/sm-core-model/pom.xml, line 435, column 13
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.salesmanager:sm-shop:war:0.0.1-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: log4j:log4j:jar -> version 1.2.16 vs 1.2.17 @ com.salesmanager:sm-shop:[unknown-version], /Users/poojawarudkar/shopizer-2.0.2/shopizer/sm-shop/pom.xml, line 355, column 16
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] sm-core
[INFO] sm-core-model
[INFO] sm-core-modules
[INFO] sm-shop
[INFO] shopizer
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building sm-core 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The artifact aspectj:aspectjrt:jar:1.5.4 has been relocated to org.aspectj:aspectjrt:jar:1.5.4
[WARNING] The artifact aspectj:aspectjweaver:jar:1.5.4 has been relocated to org.aspectj:aspectjweaver:jar:1.5.4
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ sm-core ---
[INFO] Deleting /Users/poojawarudkar/shopizer-2.0.2/shopizer/sm-core/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ sm-core ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 40 resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ sm-core ---
[INFO] Compiling 268 source files to /Users/poojawarudkar/shopizer-2.0.2/shopizer/sm-core/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ sm-core ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 6 resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ sm-core ---
[INFO] Compiling 28 source files to /Users/poojawarudkar/shopizer-2.0.2/shopizer/sm-core/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.12:test (default-test) @ sm-core ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- maven-war-plugin:2.3:war (default-war) @ sm-core ---
[INFO] Packaging webapp
[INFO] Assembling webapp [sm-core] in [/Users/poojawarudkar/shopizer-2.0.2/shopizer/sm-core/target/sm-core-0.0.1-SNAPSHOT]
[INFO] Processing war project
[INFO] Webapp assembled in [1736 msecs]
[INFO] Building war: /Users/poojawarudkar/shopizer-2.0.2/shopizer/sm-core/target/sm-core-0.0.1-SNAPSHOT.war
[INFO] 
[INFO] --- maven-install-plugin:2.3.1:install (default-install) @ sm-core ---
[INFO] Installing /Users/poojawarudkar/shopizer-2.0.2/shopizer/sm-core/target/sm-core-0.0.1-SNAPSHOT.war to /Users/poojawarudkar/.m2/repository/com/shopizer/sm-core/0.0.1-SNAPSHOT/sm-core-0.0.1-SNAPSHOT.war
[INFO] Installing /Users/poojawarudkar/shopizer-2.0.2/shopizer/sm-core/pom.xml to /Users/poojawarudkar/.m2/repository/com/shopizer/sm-core/0.0.1-SNAPSHOT/sm-core-0.0.1-SNAPSHOT.pom
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building sm-core-model 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: https://repo.maven.apache.org/maven2/org/bsc/maven/maven-processor-plugin/maven-metadata.xml
Downloaded: https://repo.maven.apache.org/maven2/org/bsc/maven/maven-processor-plugin/maven-metadata.xml (831 B at 1.7 KB/sec)
[WARNING] The artifact aspectj:aspectjrt:jar:1.5.4 has been relocated to org.aspectj:aspectjrt:jar:1.5.4
[WARNING] The artifact aspectj:aspectjweaver:jar:1.5.4 has been relocated to org.aspectj:aspectjweaver:jar:1.5.4
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ sm-core-model ---
[INFO] Deleting /Users/poojawarudkar/shopizer-2.0.2/shopizer/sm-core-model/target
[INFO] 
[INFO] --- maven-processor-plugin:3.1.0-beta1:process (process) @ sm-core-model ---
[WARNING] No processors specified. Using default discovery mechanism.
[INFO] diagnostic: Note: Hibernate JPA 2 Static-Metamodel Generator 1.1.1.Final
[WARNING] diagnostic: warning: Supported source version 'RELEASE_6' from annotation processor 'org.hibernate.jpamodelgen.JPAMetaModelEntityProcessor' less than -source '1.7'
[WARNING] diagnostic: warning: Supported source version 'RELEASE_6' from annotation processor 'org.eclipse.sisu.scanners.index.SisuIndexAPT6' less than -source '1.7'
[WARNING] diagnostic: warning: The following options were not recognized by any processor: '[addSuppressWarningsAnnotation]'
[INFO] 
[INFO] --- maven-processor-plugin:3.1.0-beta1:process (default) @ sm-core-model ---
[WARNING] No processors specified. Using default discovery mechanism.
[INFO] diagnostic: Note: Hibernate JPA 2 Static-Metamodel Generator 1.1.1.Final
[WARNING] diagnostic: warning: Supported source version 'RELEASE_6' from annotation processor 'org.hibernate.jpamodelgen.JPAMetaModelEntityProcessor' less than -source '1.7'
[WARNING] diagnostic: warning: Supported source version 'RELEASE_6' from annotation processor 'org.eclipse.sisu.scanners.index.SisuIndexAPT6' less than -source '1.7'
[INFO] 
[INFO] --- maven-apt-plugin:1.0.2:process (default) @ sm-core-model ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ sm-core-model ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/poojawarudkar/shopizer-2.0.2/shopizer/sm-core-model/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ sm-core-model ---
[INFO] Compiling 290 source files to /Users/poojawarudkar/shopizer-2.0.2/shopizer/sm-core-model/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ sm-core-model ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/poojawarudkar/shopizer-2.0.2/shopizer/sm-core-model/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ sm-core-model ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.12:test (default-test) @ sm-core-model ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- maven-war-plugin:2.3:war (default-war) @ sm-core-model ---
[INFO] Packaging webapp
[INFO] Assembling webapp [sm-core-model] in [/Users/poojawarudkar/shopizer-2.0.2/shopizer/sm-core-model/target/sm-core-model-0.0.1-SNAPSHOT]
[INFO] Processing war project
[INFO] Webapp assembled in [211 msecs]
[INFO] Building war: /Users/poojawarudkar/shopizer-2.0.2/shopizer/sm-core-model/target/sm-core-model-0.0.1-SNAPSHOT.war
[INFO] 
[INFO] --- maven-install-plugin:2.3.1:install (default-install) @ sm-core-model ---
[INFO] Installing /Users/poojawarudkar/shopizer-2.0.2/shopizer/sm-core-model/target/sm-core-model-0.0.1-SNAPSHOT.war to /Users/poojawarudkar/.m2/repository/com/shopizer/sm-core-model/0.0.1-SNAPSHOT/sm-core-model-0.0.1-SNAPSHOT.war
[INFO] Installing /Users/poojawarudkar/shopizer-2.0.2/shopizer/sm-core-model/pom.xml to /Users/poojawarudkar/.m2/repository/com/shopizer/sm-core-model/0.0.1-SNAPSHOT/sm-core-model-0.0.1-SNAPSHOT.pom
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building sm-core-modules 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ sm-core-modules ---
[INFO] Deleting /Users/poojawarudkar/shopizer-2.0.2/shopizer/sm-core-modules/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ sm-core-modules ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/poojawarudkar/shopizer-2.0.2/shopizer/sm-core-modules/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ sm-core-modules ---
[INFO] Compiling 12 source files to /Users/poojawarudkar/shopizer-2.0.2/shopizer/sm-core-modules/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ sm-core-modules ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/poojawarudkar/shopizer-2.0.2/shopizer/sm-core-modules/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ sm-core-modules ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.12:test (default-test) @ sm-core-modules ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ sm-core-modules ---
[INFO] Building jar: /Users/poojawarudkar/shopizer-2.0.2/shopizer/sm-core-modules/target/sm-core-modules-0.0.1-SNAPSHOT.jar
[INFO] 
[INFO] --- maven-install-plugin:2.3.1:install (default-install) @ sm-core-modules ---
[INFO] Installing /Users/poojawarudkar/shopizer-2.0.2/shopizer/sm-core-modules/target/sm-core-modules-0.0.1-SNAPSHOT.jar to /Users/poojawarudkar/.m2/repository/com/shopizer/sm-core-modules/0.0.1-SNAPSHOT/sm-core-modules-0.0.1-SNAPSHOT.jar
[INFO] Installing /Users/poojawarudkar/shopizer-2.0.2/shopizer/sm-core-modules/pom.xml to /Users/poojawarudkar/.m2/repository/com/shopizer/sm-core-modules/0.0.1-SNAPSHOT/sm-core-modules-0.0.1-SNAPSHOT.pom
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building sm-shop 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: http://maven.springframework.org/snapshot/com/shopizer/sm-core/2.0.2-SNAPSHOT/maven-metadata.xml
Downloading: http://maven.springframework.org/snapshot/com/shopizer/sm-core/2.0.2-SNAPSHOT/sm-core-2.0.2-SNAPSHOT.pom
[WARNING] The POM for com.shopizer:sm-core:jar:2.0.2-SNAPSHOT is missing, no dependency information available
Downloading: http://maven.springframework.org/snapshot/com/shopizer/sm-core/2.0.2-SNAPSHOT/sm-core-2.0.2-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] sm-core ............................................ SUCCESS [ 10.500 s]
[INFO] sm-core-model ...................................... SUCCESS [  9.040 s]
[INFO] sm-core-modules .................................... SUCCESS [  0.694 s]
[INFO] sm-shop ............................................ FAILURE [  0.695 s]
[INFO] shopizer ........................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 21.082 s
[INFO] Finished at: 2015-08-17T11:46:17-05:00
[INFO] Final Memory: 79M/588M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project sm-shop: Could not resolve dependencies for project com.salesmanager:sm-shop:war:0.0.1-SNAPSHOT: Could not find artifact com.shopizer:sm-core:jar:2.0.2-SNAPSHOT in org.springframework.maven.snapshot (http://maven.springframework.org/snapshot) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :sm-shop

**Comment by poojawarudkar** [comment]
R] Failed to execute goal on project sm-shop: Could not resolve dependencies for project com.salesmanager:sm-shop:war:2.0.2-SNAPSHOT: Failure to find com.shopizer:sm-core:jar:2.0.2-SNAPSHOT in http://maven.springframework.org/snapshot was cached in the local repository, resolution will not be reattempted until the update interval of org.springframework.maven.snapshot has elapsed or updates are forced -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project sm-shop: Could not resolve dependencies for project com.salesmanager:sm-shop:war:2.0.2-SNAPSHOT: Failure to find com.shopizer:sm-core:jar:2.0.2-SNAPSHOT in http://maven.springframework.org/snapshot was cached in the local repository, resolution will not be reattempted until the update interval of org.springframework.maven.snapshot has elapsed or updates are forced
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:221)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:127)
	at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:257)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:200)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project com.salesmanager:sm-shop:war:2.0.2-SNAPSHOT: Failure to find com.shopizer:sm-core:jar:2.0.2-SNAPSHOT in http://maven.springframework.org/snapshot was cached in the local repository, resolution will not be reattempted until the update interval of org.springframework.maven.snapshot has elapsed or updates are forced
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:211)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:195)
	... 23 more
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: Failure to find com.shopizer:sm-core:jar:2.0.2-SNAPSHOT in http://maven.springframework.org/snapshot was cached in the local repository, resolution will not be reattempted until the update interval of org.springframework.maven.snapshot has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:384)
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:205)
	... 24 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Failure to find com.shopizer:sm-core:jar:2.0.2-SNAPSHOT in http://maven.springframework.org/snapshot was cached in the local repository, resolution will not be reattempted until the update interval of org.springframework.maven.snapshot has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
	... 25 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Failure to find com.shopizer:sm-core:jar:2.0.2-SNAPSHOT in http://maven.springframework.org/snapshot was cached in the local repository, resolution will not be reattempted until the update interval of org.springframework.maven.snapshot has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:231)
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:206)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownloads(DefaultArtifactResolver.java:585)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:503)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
	... 27 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by umeshawasthi** [comment]
Have you tried building it after clean?
Also check if the sm-core is deployed in your local repo?

On Mon, Aug 17, 2015 at 10:24 AM, poojawarudkar <notifications@github.com>
wrote:

> R] Failed to execute goal on project sm-shop: Could not resolve
> dependencies for project com.salesmanager:sm-shop:war:2.0.2-SNAPSHOT:
> Failure to find com.shopizer:sm-core:jar:2.0.2-SNAPSHOT in
> http://maven.springframework.org/snapshot was cached in the local
> repository, resolution will not be reattempted until the update interval of
> org.springframework.maven.snapshot has elapsed or updates are forced ->
> [Help 1]
> org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute
> goal on project sm-shop: Could not resolve dependencies for project
> com.salesmanager:sm-shop:war:2.0.2-SNAPSHOT: Failure to find
> com.shopizer:sm-core:jar:2.0.2-SNAPSHOT in
> http://maven.springframework.org/snapshot was cached in the local
> repository, resolution will not be reattempted until the update interval of
> org.springframework.maven.snapshot has elapsed or updates are forced
> at
> org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:221)
> at
> org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:127)
> at
> org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:257)
> at
> org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:200)
> at
> org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
> at
> org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
> at
> org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
> at
> org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
> at
> org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
> at
> org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
> at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
> at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
> at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
> at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
> at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
> at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at
> sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
> at
> sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:606)
> at
> org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
> at
> org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
> at
> org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
> at
> org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
> Caused by: org.apache.maven.project.DependencyResolutionException: Could
> not resolve dependencies for project
> com.salesmanager:sm-shop:war:2.0.2-SNAPSHOT: Failure to find
> com.shopizer:sm-core:jar:2.0.2-SNAPSHOT in
> http://maven.springframework.org/snapshot was cached in the local
> repository, resolution will not be reattempted until the update interval of
> org.springframework.maven.snapshot has elapsed or updates are forced
> at
> org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:211)
> at
> org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:195)
> ... 23 more
> Caused by: org.eclipse.aether.resolution.DependencyResolutionException:
> Failure to find com.shopizer:sm-core:jar:2.0.2-SNAPSHOT in
> http://maven.springframework.org/snapshot was cached in the local
> repository, resolution will not be reattempted until the update interval of
> org.springframework.maven.snapshot has elapsed or updates are forced
> at
> org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:384)
> at
> org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:205)
> ... 24 more
> Caused by: org.eclipse.aether.resolution.ArtifactResolutionException:
> Failure to find com.shopizer:sm-core:jar:2.0.2-SNAPSHOT in
> http://maven.springframework.org/snapshot was cached in the local
> repository, resolution will not be reattempted until the update interval of
> org.springframework.maven.snapshot has elapsed or updates are forced
> at
> org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
> at
> org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
> at
> org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
> ... 25 more
> Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Failure
> to find com.shopizer:sm-core:jar:2.0.2-SNAPSHOT in
> http://maven.springframework.org/snapshot was cached in the local
> repository, resolution will not be reattempted until the update interval of
> org.springframework.maven.snapshot has elapsed or updates are forced
> at
> org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:231)
> at
> org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:206)
> at
> org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownloads(DefaultArtifactResolver.java:585)
> at
> org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:503)
> at
> org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
> ... 27 more
> [ERROR]
> [ERROR]
> [ERROR] For more information about the errors and possible solutions,
> please read the following articles:
> [ERROR] [Help 1]
> http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shopizer-ecommerce/shopizer/issues/36#issuecomment-131895558>
> .
>



-- 
With Regards
Umesh Awasthi
http://www.travellingrants.com/

**Comment by poojawarudkar** [comment]
Yes - running. mvn clean install -U

I think its deployed correctly. Anything particular I should be looking for?

Thanks!

**Comment by umeshawasthi** [comment]
I do not see any reason ....log saying that it is unable to find the
sm-core...
are you building master  or 2.0.2??



On Mon, Aug 17, 2015 at 11:05 AM, poojawarudkar <notifications@github.com>
wrote:

> Yes - running. mvn clean install -U
>
> I think its deployed correctly. Anything particular I should be looking
> for?
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shopizer-ecommerce/shopizer/issues/36#issuecomment-131911431>
> .
>



-- 
With Regards
Umesh Awasthi
http://www.travellingrants.com/

**Comment by poojawarudkar** [comment]
2.0.2

Thanks,

Pooja

**Comment by punj** [comment]
Still I'm unable to build and facing same problem as mohankv and poojawarudkar.

Please let me know, if it has been build successfully .

**Comment by umeshawasthi** [comment]
I was working with master and it is working fine for me....
I can chk 2.0.2.



On Tue, Aug 18, 2015 at 1:08 AM, punj <notifications@github.com> wrote:

> Still I'm unable to build and facing same problem as mohankv and
> poojawarudkar.
>
> Please let me know, if it has been build successfully .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shopizer-ecommerce/shopizer/issues/36#issuecomment-132114684>
> .
>



-- 
With Regards
Umesh Awasthi
http://www.travellingrants.com/

**Comment by punj** [comment]
What care should I take further for building it?

**Comment by muzammilhussnain14** [comment]
i'm having same issue kindly guide me to solution
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] 'dependencies.dependency.version' for com.shopizer:sm-core-model:jar must be a valid version but is '${sm-core-model.version}'. @ com.shopizer:sm-core:[unknown-version], F:\Projects\shopizer-2.0.2\shopizer\sm-core\pom.xml, line 58, column 13
[ERROR] 'dependencies.dependency.version' for com.shopizer:sm-core-modules:jar must be a valid version but is '${sm-core-modules.version}'. @ com.shopizer:sm-core:[unknown-version], F:\Projects\shopizer-2.0.2\shopizer\sm-core\pom.xml, line 65, column 13
[ERROR] 'dependencies.dependency.version' for com.shopizer:sm-search:jar must be a valid version but is '${sm-search.version}'. @ com.shopizer:sm-core:[unknown-version], F:\Projects\shopizer-2.0.2\shopizer\sm-core\pom.xml, line 72, column 13
[WARNING] 'build.pluginManagement.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.bsc.maven:maven-processor-plugin @ com.shopizer:sm-core-model:[unknown-version], F:\Projects\shopizer-2.0.2\shopizer\sm-core-model\pom.xml, line 426, column 13
[ERROR] 'dependencies.dependency.version' for com.shopizer:sm-core-model:jar must be a valid version but is '${sm-core-model.version}'. @ com.shopizer:sm-core-modules:[unknown-version], F:\Projects\shopizer-2.0.2\shopizer\sm-core-modules\pom.xml, line 30, column 13
[ERROR] 'dependencies.dependency.version' for com.shopizer:sm-core:jar must be a valid version but is '${sm-core.version}'. @ com.salesmanager:sm-shop:[unknown-version], F:\Projects\shopizer-2.0.2\shopizer\sm-shop\pom.xml, line 42, column 13
[ERROR] 'dependencies.dependency.version' for com.shopizer:sm-core-model:jar must be a valid version but is '${sm-core-model.version}'. @ com.salesmanager:sm-shop:[unknown-version], F:\Projects\shopizer-2.0.2\shopizer\sm-shop\pom.xml, line 49, column 13
[ERROR] 'dependencies.dependency.version' for com.shopizer:sm-core-modules:jar must be a valid version but is '${sm-core-modules.version}'. @ com.salesmanager:sm-shop:[unknown-version], F:\Projects\shopizer-2.0.2\shopizer\sm-shop\pom.xml, line 56, column 13
[ERROR] 'dependencies.dependency.version' for com.shopizer:sm-search:jar must be a valid version but is '${sm-search.version}'. @ com.salesmanager:sm-shop:[unknown-version], F:\Projects\shopizer-2.0.2\shopizer\sm-shop\pom.xml, line 64, column 13
[ERROR] 'dependencies.dependency.version' for com.shopizer:shopizer-shipping-canadapost-module:jar must be a valid version but is '${shopizer-canadapost.version}'. @ com.salesmanager:sm-shop:[unknown-version], F:\Projects\shopizer-2.0.2\shopizer\sm-shop\pom.xml, line 71, column 13
 @ 
[ERROR] The build could not read 3 projects -> [Help 1]
[ERROR]   
[ERROR]   The project com.shopizer:sm-core:0.0.1-SNAPSHOT (F:\Projects\shopizer-2.0.2\shopizer\sm-core\pom.xml) has 3 errors
[ERROR]     'dependencies.dependency.version' for com.shopizer:sm-core-model:jar must be a valid version but is '${sm-core-model.version}'. @ com.shopizer:sm-core:[unknown-version], F:\Projects\shopizer-2.0.2\shopizer\sm-core\pom.xml, line 58, column 13
[ERROR]     'dependencies.dependency.version' for com.shopizer:sm-core-modules:jar must be a valid version but is '${sm-core-modules.version}'. @ com.shopizer:sm-core:[unknown-version], F:\Projects\shopizer-2.0.2\shopizer\sm-core\pom.xml, line 65, column 13
[ERROR]     'dependencies.dependency.version' for com.shopizer:sm-search:jar must be a valid version but is '${sm-search.version}'. @ com.shopizer:sm-core:[unknown-version], F:\Projects\shopizer-2.0.2\shopizer\sm-core\pom.xml, line 72, column 13
[ERROR]   
[ERROR]   The project com.shopizer:sm-core-modules:0.0.1-SNAPSHOT (F:\Projects\shopizer-2.0.2\shopizer\sm-core-modules\pom.xml) has 1 error
[ERROR]     'dependencies.dependency.version' for com.shopizer:sm-core-model:jar must be a valid version but is '${sm-core-model.version}'. @ com.shopizer:sm-core-modules:[unknown-version], F:\Projects\shopizer-2.0.2\shopizer\sm-core-modules\pom.xml, line 30, column 13
[ERROR]   
[ERROR]   The project com.salesmanager:sm-shop:0.0.1-SNAPSHOT (F:\Projects\shopizer-2.0.2\shopizer\sm-shop\pom.xml) has 5 errors
[ERROR]     'dependencies.dependency.version' for com.shopizer:sm-core:jar must be a valid version but is '${sm-core.version}'. @ com.salesmanager:sm-shop:[unknown-version], F:\Projects\shopizer-2.0.2\shopizer\sm-shop\pom.xml, line 42, column 13
[ERROR]     'dependencies.dependency.version' for com.shopizer:sm-core-model:jar must be a valid version but is '${sm-core-model.version}'. @ com.salesmanager:sm-shop:[unknown-version], F:\Projects\shopizer-2.0.2\shopizer\sm-shop\pom.xml, line 49, column 13
[ERROR]     'dependencies.dependency.version' for com.shopizer:sm-core-modules:jar must be a valid version but is '${sm-core-modules.version}'. @ com.salesmanager:sm-shop:[unknown-version], F:\Projects\shopizer-2.0.2\shopizer\sm-shop\pom.xml, line 56, column 13
[ERROR]     'dependencies.dependency.version' for com.shopizer:sm-search:jar must be a valid version but is '${sm-search.version}'. @ com.salesmanager:sm-shop:[unknown-version], F:\Projects\shopizer-2.0.2\shopizer\sm-shop\pom.xml, line 64, column 13
[ERROR]     'dependencies.dependency.version' for com.shopizer:shopizer-shipping-canadapost-module:jar must be a valid version but is '${shopizer-canadapost.version}'. @ com.salesmanager:sm-shop:[unknown-version], F:\Projects\shopizer-2.0.2\shopizer\sm-shop\pom.xml, line 71, column 13
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException

**Comment by sswin** [comment]
I am getting similar issue, below are full log details,

[INFO] Scanning for projects...
[INFO] 
[INFO] Using the builder org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder with a thread count of 1
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building sm-shop 2.0.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.shopizer:sm-core:jar:2.0.2-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for com.shopizer:sm-core-model:jar:2.0.2-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for com.shopizer:sm-core-modules:jar:2.0.2-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.046 s
[INFO] Finished at: 2015-08-30T00:29:18+05:30
[INFO] Final Memory: 11M/114M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project sm-shop: Could not resolve dependencies for project com.salesmanager:sm-shop:war:2.0.2-SNAPSHOT: The following artifacts could not be resolved: com.shopizer:sm-core:jar:2.0.2-SNAPSHOT, com.shopizer:sm-core-model:jar:2.0.2-SNAPSHOT, com.shopizer:sm-core-modules:jar:2.0.2-SNAPSHOT: Failure to find com.shopizer:sm-core:jar:2.0.2-SNAPSHOT in http://maven.springframework.org/snapshot was cached in the local repository, resolution will not be reattempted until the update interval of org.springframework.maven.snapshot has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by sswin** [comment]
sorry, I didn't build sm-core earlier..getting below errors when execute mvn install,

[INFO] Downloading: http://repo.maven.apache.org/maven2/org/hamcrest/hamcrest-core/1.1/hamcrest-core-1.1.jar
[INFO] Downloaded: http://repo.maven.apache.org/maven2/org/hamcrest/hamcrest-core/1.1/hamcrest-core-1.1.jar (75 KB at 61.9 KB/sec)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 06:44 min
[INFO] Finished at: 2015-08-30T01:09:42+05:30
[INFO] Final Memory: 14M/99M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project sm-core: Could not resolve dependencies for project com.shopizer:sm-core:jar:2.0.2-SNAPSHOT: Failure to find com.shopizer:sm-core-model:jar:2.0.2-SNAPSHOT in http://maven.springframework.org/snapshot was cached in the local repository, resolution will not be reattempted until the update interval of org.springframework.maven.snapshot has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by umeshawasthi** [comment]
Can you try again by following these steps

1. Take latest update of 2.0.2
2. Clean and build

If you still face issue..my suggestion is to delete you local m2 repo and
it should fix the issue

On Sat, Aug 29, 2015 at 12:43 PM, sswin <notifications@github.com> wrote:

> sorry, I didn't build sm-core earlier..getting below errors when execute
> mvn install,
>
> [INFO] Downloading:
> http://repo.maven.apache.org/maven2/org/hamcrest/hamcrest-core/1.1/hamcrest-core-1.1.jar
> [INFO] Downloaded:
> http://repo.maven.apache.org/maven2/org/hamcrest/hamcrest-core/1.1/hamcrest-core-1.1.jar
> (75 KB at 61.9 KB/sec)
> [INFO]
> ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO]
> ------------------------------------------------------------------------
> [INFO] Total time: 06:44 min
> [INFO] Finished at: 2015-08-30T01:09:42+05:30
> [INFO] Final Memory: 14M/99M
> [INFO]
> ------------------------------------------------------------------------
> [ERROR] Failed to execute goal on project sm-core: Could not resolve
> dependencies for project com.shopizer:sm-core:jar:2.0.2-SNAPSHOT: Failure
> to find com.shopizer:sm-core-model:jar:2.0.2-SNAPSHOT in
> http://maven.springframework.org/snapshot was cached in the local
> repository, resolution will not be reattempted until the update interval of
> org.springframework.maven.snapshot has elapsed or updates are forced ->
> [Help 1]
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with the
> -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions,
> please read the following articles:
> [ERROR] [Help 1]
> http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shopizer-ecommerce/shopizer/issues/36#issuecomment-136032684>
> .
>



-- 
With Regards
Umesh Awasthi
http://www.travellingrants.com/

**Comment by sswin** [comment]
I got latest code from git into new folders, imported project as maven in eclipse lunar using main pom.xml, I ran eclipse commands maven clean, maven generate-resources, finally it is failed in maven install, also why two warningg are coming for sm-core-model, sm-core-modules,

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building sm-core 2.0.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.shopizer:sm-core-model:jar:2.0.2-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for com.shopizer:sm-core-modules:jar:2.0.2-SNAPSHOT is missing, no dependency information available
[WARNING] The artifact aspectj:aspectjrt:jar:1.5.4 has been relocated to org.aspectj:aspectjrt:jar:1.5.4
[WARNING] The artifact aspectj:aspectjweaver:jar:1.5.4 has been relocated to org.aspectj:aspectjweaver:jar:1.5.4
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.914 s
[INFO] Finished at: 2015-08-30T13:49:02+05:30
[INFO] Final Memory: 14M/178M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project sm-core: Could not resolve dependencies for project com.shopizer:sm-core:jar:2.0.2-SNAPSHOT: The following artifacts could not be resolved: com.shopizer:sm-core-model:jar:2.0.2-SNAPSHOT, com.shopizer:sm-core-modules:jar:2.0.2-SNAPSHOT: Failure to find com.shopizer:sm-core-model:jar:2.0.2-SNAPSHOT in http://maven.springframework.org/snapshot was cached in the local repository, resolution will not be reattempted until the update interval of org.springframework.maven.snapshot has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by sswin** [comment]
Also, I deleted repository folder in .m2 folder, it is failed with below error,

[INFO] Downloaded: https://repo.maven.apache.org/maven2/org/springframework/spring-test/3.1.0.RELEASE/spring-test-3.1.0.RELEASE.jar (225 KB at 146.1 KB/sec)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 20:32 min
[INFO] Finished at: 2015-08-30T14:24:54+05:30
[INFO] Final Memory: 12M/130M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project sm-core: Could not resolve dependencies for project com.shopizer:sm-core:jar:2.0.2-SNAPSHOT: The following artifacts could not be resolved: com.shopizer:sm-core-model:jar:2.0.2-SNAPSHOT, com.shopizer:sm-core-modules:jar:2.0.2-SNAPSHOT: Could not find artifact com.shopizer:sm-core-model:jar:2.0.2-SNAPSHOT in org.springframework.maven.snapshot (http://maven.springframework.org/snapshot) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by naresh1234** [comment]
Hi All....

it is working.. try to change version in pom.xml for sm-shop/pom.xml.. 

---sm-core-model.version>2.0.2
---sm-core.version>2.0.2
---sm-core-modules.version>2.0.2
---sm-search.version>0.0.4
---shopizer-canadapost.version>0.0.1

use above ones.. it will work..

**Comment by rrokka** [comment]
Thanks It helped me
