### ISSUE TITLE
Unable to install ($mvn clean install) getting following errors

### ISSUE THREAD

**Issue by muzammilhussnain14** [shopizer-ecommerce/shopizer#40]
Error log :-(
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] 'dependencies.dependency.version' for com.shopizer:sm-core-model:jar must be a valid version but is '${sm-core-model.version}'. @ com.shopizer:sm-core:[unknown-version], F:\Projects\shopizer-2.0.2\shopizer\sm-core\pom.xml, line 58, column 13
[ERROR] 'dependencies.dependency.version' for com.shopizer:sm-core-modules:jar must be a valid version but is '${sm-core-modules.version}'. @ com.shopizer:sm-core:[unknown-version], F:\Projects\shopizer-2.0.2\shopizer\sm-core\pom.xml, line 65, column 13
[ERROR] 'dependencies.dependency.version' for com.shopizer:sm-search:jar must be a valid version but is '${sm-search.version}'. @ com.shopizer:sm-core:[unknown-version], F:\Projects\shopizer-2.0.2\shopizer\sm-core\pom.xml, line 72, column 13
[WARNING] 'build.pluginManagement.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.bsc.maven:maven-processor-plugin @ com.shopizer:sm-core-model:[unknown-version], F:\Projects\shopizer-2.0.2\shopizer\sm-core-model\pom.xml, line 426, column 13
[ERROR] 'dependencies.dependency.version' for com.shopizer:sm-core-model:jar must be a valid version but is '${sm-core-model.version}'. @ com.shopizer:sm-core-modules:[unknown-version], F:\Projects\shopizer-2.0.2\shopizer\sm-core-modules\pom.xml, line 30, column 13
[ERROR] 'dependencies.dependency.version' for com.shopizer:sm-core:jar must be a valid version but is '${sm-core.version}'. @ com.salesmanager:sm-shop:[unknown-version], F:\Projects\shopizer-2.0.2\shopizer\sm-shop\pom.xml, line 42, column 13
[ERROR] 'dependencies.dependency.version' for com.shopizer:sm-core-model:jar must be a valid version but is '${sm-core-model.version}'. @ com.salesmanager:sm-shop:[unknown-version], F:\Projects\shopizer-2.0.2\shopizer\sm-shop\pom.xml, line 49, column 13
[ERROR] 'dependencies.dependency.version' for com.shopizer:sm-core-modules:jar must be a valid version but is '${sm-core-modules.version}'. @ com.salesmanager:sm-shop:[unknown-version], F:\Projects\shopizer-2.0.2\shopizer\sm-shop\pom.xml, line 56, column 13
[ERROR] 'dependencies.dependency.version' for com.shopizer:sm-search:jar must be a valid version but is '${sm-search.version}'. @ com.salesmanager:sm-shop:[unknown-version], F:\Projects\shopizer-2.0.2\shopizer\sm-shop\pom.xml, line 64, column 13
[ERROR] 'dependencies.dependency.version' for com.shopizer:shopizer-shipping-canadapost-module:jar must be a valid version but is '${shopizer-canadapost.version}'. @ com.salesmanager:sm-shop:[unknown-version], F:\Projects\shopizer-2.0.2\shopizer\sm-shop\pom.xml, line 71, column 13
 @ 
[ERROR] The build could not read 3 projects -> [Help 1]
[ERROR]   
[ERROR]   The project com.shopizer:sm-core:0.0.1-SNAPSHOT (F:\Projects\shopizer-2.0.2\shopizer\sm-core\pom.xml) has 3 errors
[ERROR]     'dependencies.dependency.version' for com.shopizer:sm-core-model:jar must be a valid version but is '${sm-core-model.version}'. @ com.shopizer:sm-core:[unknown-version], F:\Projects\shopizer-2.0.2\shopizer\sm-core\pom.xml, line 58, column 13
[ERROR]     'dependencies.dependency.version' for com.shopizer:sm-core-modules:jar must be a valid version but is '${sm-core-modules.version}'. @ com.shopizer:sm-core:[unknown-version], F:\Projects\shopizer-2.0.2\shopizer\sm-core\pom.xml, line 65, column 13
[ERROR]     'dependencies.dependency.version' for com.shopizer:sm-search:jar must be a valid version but is '${sm-search.version}'. @ com.shopizer:sm-core:[unknown-version], F:\Projects\shopizer-2.0.2\shopizer\sm-core\pom.xml, line 72, column 13
[ERROR]   
[ERROR]   The project com.shopizer:sm-core-modules:0.0.1-SNAPSHOT (F:\Projects\shopizer-2.0.2\shopizer\sm-core-modules\pom.xml) has 1 error
[ERROR]     'dependencies.dependency.version' for com.shopizer:sm-core-model:jar must be a valid version but is '${sm-core-model.version}'. @ com.shopizer:sm-core-modules:[unknown-version], F:\Projects\shopizer-2.0.2\shopizer\sm-core-modules\pom.xml, line 30, column 13
[ERROR]   
[ERROR]   The project com.salesmanager:sm-shop:0.0.1-SNAPSHOT (F:\Projects\shopizer-2.0.2\shopizer\sm-shop\pom.xml) has 5 errors
[ERROR]     'dependencies.dependency.version' for com.shopizer:sm-core:jar must be a valid version but is '${sm-core.version}'. @ com.salesmanager:sm-shop:[unknown-version], F:\Projects\shopizer-2.0.2\shopizer\sm-shop\pom.xml, line 42, column 13
[ERROR]     'dependencies.dependency.version' for com.shopizer:sm-core-model:jar must be a valid version but is '${sm-core-model.version}'. @ com.salesmanager:sm-shop:[unknown-version], F:\Projects\shopizer-2.0.2\shopizer\sm-shop\pom.xml, line 49, column 13
[ERROR]     'dependencies.dependency.version' for com.shopizer:sm-core-modules:jar must be a valid version but is '${sm-core-modules.version}'. @ com.salesmanager:sm-shop:[unknown-version], F:\Projects\shopizer-2.0.2\shopizer\sm-shop\pom.xml, line 56, column 13
[ERROR]     'dependencies.dependency.version' for com.shopizer:sm-search:jar must be a valid version but is '${sm-search.version}'. @ com.salesmanager:sm-shop:[unknown-version], F:\Projects\shopizer-2.0.2\shopizer\sm-shop\pom.xml, line 64, column 13
[ERROR]     'dependencies.dependency.version' for com.shopizer:shopizer-shipping-canadapost-module:jar must be a valid version but is '${shopizer-canadapost.version}'. @ com.salesmanager:sm-shop:[unknown-version], F:\Projects\shopizer-2.0.2\shopizer\sm-shop\pom.xml, line 71, column 13
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException

**Comment by wo3002807** [comment]
The Problem that I met is complicate. Maybe It has specified value in the version, such as <sm-core.version>2.0.2</sm-core.version>. But I don't know the values about the version. Maybe the Author can explain that why. 
By the way, I hope Someone who figure out the reasion should share how to install shopizer 2.0.2 exactly.

**Comment by wo3002807** [comment]
I figure out there. The Author submit the new /shopizer/pom.xml file. You need to edit that file with add specified content. 
The content as follow:
  <properties>  
      <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>  
                <shopizer.version>2.0.2-SNAPSHOT</shopizer.version>  
                <sm-core.version>2.0.2-SNAPSHOT</sm-core.version>  
                <sm-core-model.version>2.0.2-SNAPSHOT</sm-core-model.version>  
                 <sm-core-modules.version>2.0.2-SNAPSHOT</sm-core-modules.version>  
                <sm-search.version>0.0.4</sm-search.version>  
                 <sm-shop.version>2.0.2-SNAPSHOT</sm-shop.version>  
                <shopizer-canadapost.version>0.0.1</shopizer-canadapost.version>	  
    </properties>  
=======================================================
The problem will not happen again  when you will compile all the file. But another problem also happen. You should look at the new file The author submit And modifies. That is all.

**Comment by umeshawasthi** [comment]
Problem should be fixed with the changes..Please try to clean and build it again..if problem still remains try to delete m2 local repo and build again

**Comment by shopizer-ecommerce** [comment]
The issue was with the zip download, it has been resolved

**Comment by mailmeprash** [comment]
mvn install in sm-shop is still not working with above changes. can you please mail me latest zip file link.

**Comment by shopizer-ecommerce** [comment]
Fixed in 2.0.3

**Comment by binayrs** [comment]
Hi,

I am getting the same issue but in pom.xml of module 'sm-core-model'. Can you check and help me for the solution ?

Below is the stacktrace.
[WARNING] Some problems were encountered while building the effective model for com.shopizer:sm-core-model:jar:2.0.3-SNAPSHOT
[WARNING] 'build.pluginManagement.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.bsc.maven:maven-processor-plugin @ com.shopizer:sm-core-model:[unknown-version], D:\Workspace\Shopizer\shopizer\sm-core-model\pom.xml, line 430, column 13
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] shopizer
[INFO] sm-core-model
[INFO] sm-core-modules
[INFO] sm-core
[INFO] sm-shop
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building shopizer 2.0.3-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] shopizer ........................................... FAILURE [  0.000 s]
[INFO] sm-core-model ...................................... SKIPPED
[INFO] sm-core-modules .................................... SKIPPED
[INFO] sm-core ............................................ SKIPPED
[INFO] sm-shop ............................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.282 s
[INFO] Finished at: 2016-06-28T07:56:56+05:30
[INFO] Final Memory: 7M/115M
[INFO] ------------------------------------------------------------------------
[ERROR] Unknown lifecycle phase "switch". You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]
org.apache.maven.lifecycle.LifecyclePhaseNotFoundException: Unknown lifecycle phase "switch". You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy.
	at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.calculateLifecycleMappings(DefaultLifecycleExecutionPlanCalculator.java:246)
	at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.calculateMojoExecutions(DefaultLifecycleExecutionPlanCalculator.java:217)
	at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.calculateExecutionPlan(DefaultLifecycleExecutionPlanCalculator.java:127)
	at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.calculateExecutionPlan(DefaultLifecycleExecutionPlanCalculator.java:145)
	at org.apache.maven.lifecycle.internal.builder.BuilderCommon.resolveBuildPlan(BuilderCommon.java:96)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:109)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/LifecyclePhaseNotFoundException
