### ISSUE TITLE
Could not resolve dependencies com.shopizer:sm-search:jar:0.0.5-SNAPSHOT, com.shopizer:shopizer-shipping-distance-processor:jar:0.0.1

### ISSUE THREAD

**Issue by muzammilhussnain14** [shopizer-ecommerce/shopizer#41]
Mvn clean install master getting this dependence error
[ERROR] Failed to execute goal on project sm-core: Could not resolve dependencies for project com.shopizer:sm-core:jar:2.0.3-SNAPSHOT: The following artifacts could not be resolved: com.shopizer:sm-search:jar:0.0.5-SNAPSHOT, com.shopizer:shopizer-shipping-distance-processor:jar:0.0.1: Failure to find com.shopizer:sm-search:jar:0.0.5-SNAPSHOT in http://maven.springframework.org/snapshot was cached in the local repository, resolution will not be reattempted until the update interval of org.springframework.maven.snapshot has elapsed or updates are forced -> [Help 1]

**Comment by umeshawasthi** [comment]
@muzammilhussnain14 
try by cleaning and removing the maven repo and try to build again.This should fix the issue

**Comment by muzammilhussnain14** [comment]
@umeshawasthi 
I have tried mvn clean and than mvn install but it has not solved the Problem thanks for the reply

**Comment by umeshawasthi** [comment]
@muzammilhussnain14 
Can you share all the pom.xml ? I want to have look at it

**Comment by muzammilhussnain14** [comment]
@umeshawasthi Yes sure here is the pom.xml of core module
<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>com.shopizer</groupId>
    <artifactId>shopizer</artifactId>
    <version>2.0.3-SNAPSHOT</version>
  </parent>

	<artifactId>sm-core</artifactId>
	
	<packaging>jar</packaging>

	<name>sm-core</name>
	<url>http://www.shopizer.com</url>

	<properties>
	
		 
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		
		<jackson-version>1.9.13</jackson-version>
		<axis-version>1.4</axis-version>
		<jaxws.api.version>2.1</jaxws.api.version>
		<jaxws.version>2.1.4</jaxws.version>
		<jsr181.version>1.0-MR1</jsr181.version>
		<jsr250.version>1.0</jsr250.version>
		<io.searchbox.jest-version>0.1.5</io.searchbox.jest-version>
		<guava.version>18.0</guava.version>
        <gson.version>2.3.1</gson.version>
		
		<jasperreports-version>3.7.4</jasperreports-version>
		
		<freemarker.version>2.3.19</freemarker.version>
		<org.slf4j-version>1.6.6</org.slf4j-version>
		<hibernate.ehcache.version>3.5.1-Final</hibernate.ehcache.version>
		<sm-core.drools.version>5.6.0.Final</sm-core.drools.version>
		<sm-core.hibernate-entitymanager-version>4.1.2</sm-core.hibernate-entitymanager-version>
		<sm-core.aspectj.version>1.5.4</sm-core.aspectj.version>
		<sm-core.mysql-connector-java>5.1.31</sm-core.mysql-connector-java>
		<sm-core.junit.version>4.9</sm-core.junit.version>
		<sm-core.org.springframework.version>3.1.0.RELEASE</sm-core.org.springframework.version>
		<sm-core.c3p0.version>0.9.1.2</sm-core.c3p0.version>
		<sm-core.querydsl.version>3.4.2</sm-core.querydsl.version>
		<sm-core.jodatime.version>2.0</sm-core.jodatime.version>
		<sm-core.jodatime-hibernate.version>1.3</sm-core.jodatime-hibernate.version>
		<sm-core.javassist.version>3.3</sm-core.javassist.version>
	</properties>

	<dependencies>
	
		
		
		<dependency>
			<groupId>com.shopizer</groupId>
			<artifactId>sm-core-model</artifactId>
			<version>${sm-core-model.version}</version>
		</dependency>

		
		<dependency>
			<groupId>com.shopizer</groupId>
			<artifactId>sm-core-modules</artifactId>
			<version>${sm-core-modules.version}</version>
		</dependency>

	    		
		<dependency>
			<groupId>com.shopizer</groupId>
			<artifactId>sm-search</artifactId>
			<version>${sm-search.version}</version>
		</dependency>
		
		
		
 		<dependency>
			<groupId>com.shopizer</groupId>
			<artifactId>shopizer-shipping-distance-processor</artifactId>
			<version>0.0.1</version>
		</dependency>
		
		
		<dependency>
			<groupId>com.shopizer</groupId>
			<artifactId>shopizer-shipping-canadapost-module</artifactId>
			<version>0.0.1</version>
		</dependency>

		
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-log4j12</artifactId>
			<version>${org.slf4j-version}</version>
		</dependency>
		
		
		<dependency>
    		<groupId>cglib</groupId>
			<artifactId>cglib</artifactId>
			<version>2.2</version>
    	</dependency>

		
		<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-core</artifactId>
			<version>${sm-core.hibernate-entitymanager-version}</version>
			<exclusions>
				<exclusion>
					<artifactId>javassist</artifactId>
					<groupId>org.javassist</groupId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-entitymanager</artifactId>
			<version>${sm-core.hibernate-entitymanager-version}</version>
			<exclusions>
				<exclusion>
					<groupId>asm</groupId>
					<artifactId>asm</artifactId>
				</exclusion>
				<exclusion>
					<groupId>asm</groupId>
					<artifactId>asm-attrs</artifactId>
				</exclusion>
				<exclusion>
					<groupId>cglib</groupId>
					<artifactId>cglib</artifactId>
				</exclusion>
				<exclusion>
					<artifactId>javassist</artifactId>
					<groupId>javassist</groupId>
				</exclusion>
				<exclusion>
					<groupId>org.hibernate</groupId>
					<artifactId>hibernate-core</artifactId>
				</exclusion>
				<exclusion>
					<artifactId>javassist</artifactId>
					<groupId>org.javassist</groupId>
				</exclusion>
			</exclusions>
		</dependency>

		
		<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-ehcache</artifactId>
			<version>${hibernate.ehcache.version}</version>
		</dependency>

		
		<dependency>
			<groupId>javassist</groupId>
			<artifactId>javassist</artifactId>
			<version>${sm-core.javassist.version}</version>
		</dependency>

		
		<dependency>
			<groupId>com.mysema.querydsl</groupId>
			<artifactId>querydsl-apt</artifactId>
			<version>${sm-core.querydsl.version}</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>com.mysema.querydsl</groupId>
			<artifactId>querydsl-core</artifactId>
			<version>${sm-core.querydsl.version}</version>
		</dependency>
		<dependency>
			<groupId>com.mysema.querydsl</groupId>
			<artifactId>querydsl-jpa</artifactId>
			<version>${sm-core.querydsl.version}</version>
		</dependency>

		
		<dependency>
			<groupId>c3p0</groupId>
			<artifactId>c3p0</artifactId>
			<version>${sm-core.c3p0.version}</version>
		</dependency>

		
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-aop</artifactId>
			<version>${sm-core.org.springframework.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-aspects</artifactId>
			<version>${sm-core.org.springframework.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-beans</artifactId>
			<version>${sm-core.org.springframework.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-context</artifactId>
			<version>${sm-core.org.springframework.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-core</artifactId>
			<version>${sm-core.org.springframework.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-expression</artifactId>
			<version>${sm-core.org.springframework.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-orm</artifactId>
			<version>${sm-core.org.springframework.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-web</artifactId>
			<version>${sm-core.org.springframework.version}</version>
		</dependency>

		
		<dependency>
			<groupId>javax.validation</groupId>
			<artifactId>validation-api</artifactId>
			<version>1.0.0.GA</version>
		</dependency>
		<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-validator</artifactId>
			<version>4.3.0.Final</version>
		</dependency>

		
		<dependency>
			<groupId>aspectj</groupId>
			<artifactId>aspectjrt</artifactId>
			<version>${sm-core.aspectj.version}</version>
		</dependency>
		<dependency>
			<groupId>aspectj</groupId>
			<artifactId>aspectjweaver</artifactId>
			<version>${sm-core.aspectj.version}</version>
		</dependency>

		
		<dependency>
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>
			<version>${sm-core.mysql-connector-java}</version>
		</dependency>
		
		
		<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
			<version>1.3.152</version>
		</dependency>


		
		<dependency>
			<groupId>org.codehaus.jackson</groupId>
			<artifactId>jackson-mapper-asl</artifactId>
			<version>${jackson-version}</version>
		</dependency>
		<dependency>
			<groupId>com.googlecode.json-simple</groupId>
			<artifactId>json-simple</artifactId>
			<version>1.1.1</version>
		</dependency>

		
		<dependency>
			<groupId>commons-fileupload</groupId>
			<artifactId>commons-fileupload</artifactId>
			<version>1.2.2</version>
		</dependency>
		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
			<version>2.0.1</version>
		</dependency>

		<dependency>
			<groupId>commons-collections</groupId>
			<artifactId>commons-collections</artifactId>
			<version>3.2.1</version>
	   </dependency>
	   
		
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
			<version>3.0</version>
		</dependency>
		
		<dependency>
			<groupId>commons-validator</groupId>
			<artifactId>commons-validator</artifactId>
			<version>1.4.0</version>
		</dependency>
		
		
		<dependency>
			<groupId>org.drools</groupId>
			<artifactId>drools-spring</artifactId>
			<version>${sm-core.drools.version}</version>
		</dependency>

		
		<dependency>
			<groupId>commons-lang</groupId>
			<artifactId>commons-lang</artifactId>
			<version>2.6</version>
		</dependency>


		<dependency>
			<groupId>commons-httpclient</groupId>
			<artifactId>commons-httpclient</artifactId>
			<version>3.1</version>
		</dependency>

		

		
		<dependency>
			<groupId>joda-time</groupId>
			<artifactId>joda-time</artifactId>
			<version>${sm-core.jodatime.version}</version>
		</dependency>
		<dependency>
			<groupId>org.jadira.usertype</groupId>
			<artifactId>usertype.core</artifactId>
			<version>3.0.0.CR1</version>
		</dependency>


        
  		<dependency>
			<groupId>org.infinispan</groupId>
    		<artifactId>infinispan-core</artifactId>
    		<version>5.1.6.FINAL</version>
  		</dependency>

		<dependency>      
			<groupId>org.infinispan</groupId>      
			<artifactId>infinispan-cachestore-jdbc</artifactId>      
			<version>5.1.4.FINAL</version>
		</dependency> 
		
		<dependency>
			<groupId>org.infinispan</groupId>
			<artifactId>infinispan-tree</artifactId>
			<version>5.1.6.FINAL</version>
		</dependency>

		<dependency>
			<groupId>org.freemarker</groupId>
			<artifactId>freemarker</artifactId>
			<version>${freemarker.version}</version>
		</dependency>
		
		<dependency>
			<groupId>javax.mail</groupId>
			<artifactId>mail</artifactId>
			<version>1.4.5</version>
		</dependency>
		

		<dependency>
			<groupId>org.jopendocument</groupId>
			<artifactId>jOpenDocument</artifactId>
			<version>1.3b1</version>
		</dependency>
		
		


		<dependency>
			<groupId>com.itextpdf</groupId>
			<artifactId>itextpdf</artifactId>
			<version>5.5.6</version>
		</dependency>
		
		
		
		
		
		<dependency>
			<groupId>com.paypal.sdk</groupId>
			<artifactId>merchantsdk</artifactId>
			<version>2.6.109</version>
		</dependency>
		
	    <dependency>
	        <groupId>com.maxmind.geoip2</groupId>
	        <artifactId>geoip2</artifactId>
	        <version>0.7.0</version>
	    </dependency>
	    
		
		<dependency>
			<groupId>io.searchbox</groupId>
			<artifactId>jest</artifactId>
			<version>${io.searchbox.jest-version}</version>
		</dependency>

		<dependency>
                <groupId>com.google.guava</groupId>
                <artifactId>guava</artifactId>
                <version>${guava.version}</version>
         </dependency>

         <dependency>
                <groupId>com.google.code.gson</groupId>
                <artifactId>gson</artifactId>
                <version>${gson.version}</version>
          </dependency>
			
		
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>${sm-core.junit.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-test</artifactId>
			<version>${sm-core.org.springframework.version}</version>
			<scope>test</scope>
		</dependency>

		
	</dependencies>
	
	<repositories>	
		
		<repository>
			<id>org.springframework.maven.snapshot</id>
			<name>Spring Maven Snapshot Repository</name>
			<url>http://maven.springframework.org/snapshot</url>
			<releases><enabled>false</enabled></releases>
			<snapshots><enabled>true</enabled></snapshots>
		</repository>
		
		<repository>
			<id>org.springframework.maven.milestone</id>
			<name>Spring Maven Milestone Repository</name>
			<url>http://maven.springframework.org/milestone</url>
			<snapshots><enabled>false</enabled></snapshots>
		</repository>
		<repository>
			<id>org.jboss.repository.releases</id>
			<name>JBoss Maven Release Repository</name>			
			<url>https://repository.jboss.org/nexus/content/repositories/releases</url>
			<snapshots><enabled>false</enabled></snapshots>			
		</repository>
	</repositories>

	<build>
		
		<plugins>
			
		</plugins>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-compiler-plugin</artifactId>
					<version>3.2</version>
					<configuration>
						<source>${jdk-version}</source>
						<target>${jdk-version}</target>
						<encoding>${project.build.sourceEncoding}</encoding>
						<compilerArgument>-proc:none</compilerArgument>
					</configuration>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-surefire-plugin</artifactId>
					<version>2.12</version>
					<configuration>
          				<skipTests>true</skipTests>
        			</configuration>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-war-plugin</artifactId>
					<version>2.2</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-install-plugin</artifactId>
					<version>2.3.1</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-release-plugin</artifactId>
					<version>2.2.2</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-assembly-plugin</artifactId>
					<version>2.3</version>
				</plugin>
				
				
				
				
				<plugin>
					<groupId>org.codehaus.mojo</groupId>
					<artifactId>hibernate3-maven-plugin</artifactId>
					<version>2.2</version>
					<executions>
						<execution>
							<phase>process-classes</phase>
							<goals>
								<goal>hbm2ddl</goal>
							</goals>
						</execution>
					</executions>
					<configuration>
						<components>
							<component>
								<name>hbm2ddl</name>
								<implementation>jpaconfiguration</implementation>
							</component>
						</components>
						<componentProperties>
							<persistenceunit>sm-unit</persistenceunit>
							
							<outputfilename>schema.ddl</outputfilename>
							<drop>false</drop>
							<create>true</create>
							<export>false</export>
							<format>true</format>
						</componentProperties>
					</configuration>
				</plugin>
				
				<plugin>
					<groupId>org.eclipse.m2e</groupId>
					<artifactId>lifecycle-mapping</artifactId>
					<version>1.0.0</version>
					<configuration>
						<lifecycleMappingMetadata>
							<pluginExecutions>
								<pluginExecution>
									<pluginExecutionFilter>
										<groupId>org.codehaus.mojo</groupId>
										<artifactId>aspectj-maven-plugin</artifactId>
										<versionRange>[1.0,)</versionRange>
										<goals>
											<goal>test-compile</goal>
											<goal>compile</goal>
										</goals>
									</pluginExecutionFilter>
									<action>
										<execute />
									</action>
								</pluginExecution>
							</pluginExecutions>
						</lifecycleMappingMetadata>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>
</project>

**Comment by umeshawasthi** [comment]
@muzammilhussnain14
Can you send me these by email..I need all the pom files (umeshawasthi@gmail.com)

**Comment by muzammilhussnain14** [comment]
@umeshawasthi I have sent all 5 pom files on given email kindly find my email muzammilh0786@gmail.com from your inbox. I will be grateful to you.

and kindly can you suggest me good video tutorials for java spring. I have experience in java se and java2ee struts but I came to know spring is best for j2ee.
Thanks

**Comment by yuzhiping** [comment]
i have the same problem,did you ( @muzammilhussnain14 ) solve it? if you sovle it can you provide some suggest?

**Comment by yuzhiping** [comment]
@umeshawasthi   did you solve the problem ,can you give some help?

**Comment by chidambaramnarayan** [comment]
@umeshawasthi I have the same problem

ERROR] Failed to execute goal on project sm-core: Could not resolve dependencies for project com.shopizer:sm-core:jar:2.0.3-SNAPSHOT: The following artifacts could not be resolved: com.shopizer:sm-search:jar:0.0.5-SNAPSHOT, com.shopizer:shopizer-shipping-distance-processor:jar:0.0.1: Could not find artifact com.shopizer:sm-search:jar:0.0.5-SNAPSHOT in org.springframework.maven.snapshot (http://maven.springframework.org/snapshot) -> [Help 1]

**Comment by chidambaramnarayan** [comment]
Hi Umesh any update

**Comment by daveyx** [comment]
Hi,
The following artifacts could not be resolved: com.shopizer:sm-search:jar:0.0.5-SNAPSHOT issue can be fixed by:
https://groups.google.com/forum/#!topic/shopizer/RbNhKqHNEVU
i.e. build shopizer-search by your self

but building masterbranch i get another missing artifact issue for com.shopizer:shopizer-shipping-distance-processor:jar:0.0.1

i am still not able to build masterbranch or 2.0.2 branch

**Comment by daveyx** [comment]
here a version 2.0.3 for shopizer-shipping-distance-processor  https://maven-repository.com/artifact/com.shopizer/shopizer-shipping-distance-processor/2.0.3 available, so changing from 0.0.1 to version 2.0.3 in pom in sm-core let the master build

**Comment by umeshawasthi** [comment]
This has been fixed in 2.0.3 release. Please test with new release
